#docker rm -f socketserver
#docker run --restart=always --name socketserver -d -p 4567:4567 hhoareau/socketserverarm
#docker run --restart=always --name socketserver -d -p 4567:4567 hhoareau/socketserverarm http://localhost:8080
#docker run -t -p 4567:4567 --name socketserver hhoareau/socketserverarm http://localhost:8080
#docker run -t -p 4567:4567 --name socketserver hhoareau/socketserverarm
#sudo docker build -t hhoareau/socketserverarm .
#sudo docker push hhoareau/socketserverarm
#sudo docker pull hhoareau/socketserverarm
#test de l'appli java -cp ShifuMicroServer.jar SparkApplication v1 http://localhost:8080 5271 c:/temp http://localhost
#java -cp socketserver.jar SockServer http://localhost:8080 4567
#java -cp socketserver.jar SockServer http://shifumixweb.appspot.com 4567

FROM hypriot/rpi-java

RUN sudo apt-get update
RUN sudo apt-get upgrade

RUN sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure

ADD *.jar .
ADD *.jks .

EXPOSE 4567
CMD ["java", "-cp", "./socketserver.jar","SockServer","https://shifumixweb.appspot.com","4567","alpha.shifumix.com"]
